### PR TITLE
update readme to include NSMicrophoneUsageDescription if needed

### PR DESCRIPTION
**Pull request by arielelkin**

### CODE REVIEW

**Comment by anuragajwani** [comment]
@arielelkin thanks for the pull request. We have been informed by other integrators that App Store rejects the SDK if the microphone permission key is not present in the Info.plist regardless of having face capture video variant configured. Can you confirm that this is not the case anymore please?

**Comment by arielelkin** [comment]
@anuragajwani as you can see from Apple's [documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription), including the `NSMicrophoneUsageDescription` key in Info.plist is only required if the app uses APIs that use the device's microphone. 

The only media-capturing functionality in our app is done by the Onfido SDK, so can you please tell us whether setting up a flow like this:

```swift
let config = try! OnfidoConfig.builder()
    .withToken("YOUR_TOKEN_HERE")
    .withApplicantId("APPLICANT_ID_HERE")
    .withWelcomeStep()
    .withDocumentStep()
    .withFaceStep(ofVariant: .photo)
    .build()
```

will result in the OnfidoSDK using the device's microphone?

**Comment by arielelkin** [comment]
@anuragajwani any updates?

**Comment by anuragajwani** [comment]
@arielelkin we want to check this with our team that has released an App to the App Store using the SDK. The engineer who has done the releases is on vacation and we are waiting for his return.

Sorry for the delay,
Anurag

**Comment by fphilipe** [comment]
@anuragajwani any updates on this? I'm facing the same situation here.

**Comment by anuragajwani** [comment]
@fphilipe are you doing face photo capture only? Could you confirm that microphone usage key is not needed in the Info.plist file?

Thanks for your input,
Anurag

**Comment by fphilipe** [comment]
> are you doing face photo capture only?

Yes.

> Could you confirm that microphone usage key is not needed in the Info.plist file?

Not there yet. But I guess the app would crash if it's not in the Info.plist (if I recall correctly, that's what happens with the camera permission).

Will report back.

**Comment by crilofer** [comment]
Hi,

Our app has been just rejected by App Store due to not include the `NSMicrophoneUsageDescription` in Info.plist file.

I think both keys are mandatories.

**Comment by keremgund** [comment]
As confirmed with other developers here, Apple expects to add both keys regardless of what happens during runtime.

**Pull request closed without merging**
